### ISSUE TITLE
ETC - Ajouter une page de sélection du département

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1044]
ETC, je suis redirigé sur la page de sélection du département :
- [x] Visibilité de la liste de tous les départements dispo sur Candilib avec le nombre de places disponibles
- [x] Choix du département géographique
- [x] Affichage de la liste des centres rattachés au département géographique (chaque centre apparaît autant de fois qu'il est lié à un département, avec les places mises à dispositions par le BER dudit département)
- [x] Si aucune place dispo dans le département, le département est cliquable mais le centre ne l'est pas
- [x] Les départements qui n'ont pas de centre ne sont pas donc pas affichés (ex : le 75)

**Comment by Evbern** [comment]
![image](https://user-images.githubusercontent.com/48919541/77409473-9ab2ae00-6db9-11ea-935f-cfd4f59f029c.png)

**Comment by baudointran** [comment]
API:
- [ ] Retirer le filtre de département pour le candidat
- [ ] Ajouter un département géographique dans le model des centres
- [ ] Compter les places par département géographie
- [ ] Modifier le département administratif lors de la réservation 
- [ ] 

FRONT: en entonnoir
- [ ] Route pour département
