### ISSUE TITLE
ETC - Formulaire : composition page (5)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1087]
ETC, je souhaite contacter l'administration relativement à Candilib.

Je peux réaliser cette action via un formulaire dédié, depuis la FAQ (position inchangée) via le formulaire composé comme suit.

**Je renseigne les infos obligatoires suivantes**
- [x] Déjà pré-inscrit ou inscrit sur le site Candilib (coche)
- [x] NEPH (txt)
- [x] Nom (txt)
- [x] Mail (adresse mail utilisée lors de votre inscription, si applicable) (txt ; vérif de la forme)
- [x] Département de résidence (liste déroulante des départements administratifs ouverts)
- [x] Objet du message (txt)
- [x] Message (txt)

**Je valide ma demande**
- [x] Je clique sur le bouton Envoyer
- [ ] Je peux fermer le formulaire en cliquant sur le bouton précédant

**Le mail est envoyé à la BAL fonctionnelle du BER concerné**
- [ ] Si le candidat n'est pas connu, le mail est envoyé à la BAL du département de résidence du formulaire
- [ ] Si le candidat n'a pas encore validé son mail, le mail est envoyé à la BAL du département de résidence du formulaire
- [ ] Si le candidat est pré-inscrit et que le batch Aurige n'est pas encore passé, le candidat est considéré comme tel et le mail est envoyé à la BAL du département administratif de rattachement
- [ ] Si le candidat est inscrit, le mail est envoyé à la BAL du département administratif de rattachement

_La suite : je reçois un mail de confirmation #1089_

![image](https://user-images.githubusercontent.com/48919541/78901894-470eb880-7a79-11ea-9c94-2d0d15dc64e2.png)

**Comment by baudointran** [comment]
FRONT:
- [ ] Route à créer pour accéder au formulaire
- [ ] Page créer
- [ ] Régle 1: un token => Les infos du candidat se remplie automatiquement
- [ ] Régle 2: pas token => Saisi des info par l'utilisateur
- [ ] Tous les champs sont obligatoires

**Comment by baudointran** [comment]
API:
[ ] Récupérer le département de administratif du candidat dans la base de données sinon sera celui du formulaire

**Comment by baudointran** [comment]
Page un candidat non conncté

![image](https://user-images.githubusercontent.com/16351036/80379030-d26fb280-889d-11ea-9023-b08ccc806793.png)

**Comment by baudointran** [comment]
Pour un candidat connecté

![image](https://user-images.githubusercontent.com/16351036/80379416-5c1f8000-889e-11ea-8623-2b0cb2220354.png)

**Comment by baudointran** [comment]
Voici le copie d'écran après avoir incorporer les corrections lié au changement de département

![image](https://user-images.githubusercontent.com/16351036/80600921-5d32e780-8a2d-11ea-8506-d8eb1626a42e.png)
