### ISSUE TITLE
ETD - Compléter la fiche candidat (avec précisions sur les départements)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#1095]
ETD / ETR, je souhaite pouvoir disposer de l'historique des changements de départements du candidat dans sa fiche.

Il convient d'apporter les ajustements suivants

Historique
- [ ] Afficher le département administratif à la suite de chaque **annulation/modification réalisée par le candidat**, avec le nom de l'IPCSR
- [x] Afficher le département administratif à la suite de chaque **annulation/modification réalisée par l'administration** sous le forme _prénom.nom de l'administrateur + numéro du département_
- [x] Afficher le département administratif à la suite de chaque **réservation réalisée par l'administration**, sous le forme _prénom.nom  de l'administrateur + numéro du département_

Réservation en cours
- [x] Afficher pour la **réservation en cours** du candidat : date heure, centre, département administratif

_Travail en cours pour synthétiser l'affichage de l'historique (métier)_

**Comment by baudointran** [comment]
TECH:
- [ ]  Vérifier s'il y a un flag Modification pour la modification d'une réservation  d'un candidat

**Comment by Evbern** [comment]
OK pour les 3 derniers points.

Néanmoins, PB pour vérifier le premier.
Après avoir annulé un examen (en tant qu'admin) pour TEST.75, je me suis connecté en tant que TEST.75 pour choisir un nouveau créneau d'examen. Mais c'est impossible est j'ai systématiquement un message comme quoi la place est déjà réservée, alors qu'elle est en réalité disponible (cf. screenshots)

**Comment by Evbern** [comment]
![Capture d’écran 2020-07-30 à 20 12 27](https://user-images.githubusercontent.com/48919541/88959032-a8b19780-d2a1-11ea-8529-941c6ee63154.png)

**Comment by Evbern** [comment]
![Capture d’écran 2020-07-30 à 20 14 35](https://user-images.githubusercontent.com/48919541/88959154-d5fe4580-d2a1-11ea-901e-4c9fc1453fe0.png)

**Comment by Evbern** [comment]
PI, @BCARPANO-nov
