### ISSUE TITLE
Rechercher un candidat

### ISSUE THREAD

**Issue by Fredsr** [LAB-MI/candilibV2#255]
je veux une barre de recherche alphabétique et numérique pour

- [x] rechercher un candidat par son nom, prénom, neph, email

Dans la page de réponse, je veux pouvoir accéder à toutes les infos du candidat par ordre chronologique de ses actions : 

- [x] inscription, date et toutes ses infos, nom, prénom, adresse, courriel, tel, date de validité de l'ETG ...

- [x] réservation, dates (de la résa et du jour de résa), horaires, centre, ipcsr

**Comment by laruiss** [comment]
Il faudrait décomposer ce ticket : tout ce qui est coché sera en 2.0, le reste n'est pas primordial et ne devrait pas être en 2.0, mais au moins en 2.1 (voir plus)

**Comment by Evbern** [comment]
@laruiss ok done
