### ISSUE TITLE
Modifier l'IPCSR sur un créneau réservé

### ISSUE THREAD

**Issue by Fredsr** [LAB-MI/candilibV2#257]
ETD, je peux modifier l'inspecteur sur la réservation d'un candidat pour le même horaire, même centre, même date afin d'optimiser le planning d'un inspecteur (ex : sur un centre, un inspecteur A n'a qu'un seul examen à faire passer le 15/04 de 10h à 10h30 alors qu'un inspecteur B a un créneau disponible sur ce même centre, le même jour au même horaire).

 (ne sont proposés que les inspecteurs disponibles sur le même horaire, le même centre, même date) un créneau réservé suite à un empêchement incombant à l'administration (ex : absence d'un inspecteur, erreur de disponibilité dans le CSV repérée tardivement).

- [x] je clique sur un créneau réservé
- [x] une popup apparaît et me propose de modifier l'IPCSR ou d'annuler l'action (via une croix)

Si je modifie l'IPCSR
- [x] une barre permet de rechercher les IPCSR par son matricule ou son nom
- [x] seuls les IPCSR disponibles sur le même centre, le même jour, au même horaire sont proposés (affichage du nom et du matricule)
- [x] je peux choisir le nouvel IPCSR en cliquant sur son matricule ou son nom
- [x] je confirme le changement
- [x] aucun mail n'est envoyé au candidat (cette modification d'IPCSR est transparente pour lui)
- [x] lorsque je reviens sur le planning général, le créneau est réservé pour le nouvel IPCSR positionné et le créneau est disponible pour l'IPCSR initialement positionné

Si j'annule mon action
- [x] la pop-up disparaît et j'ai de nouveau accès au planning

**Comment by Evbern** [comment]
![DSR - Candilib admin gplanning](https://user-images.githubusercontent.com/48919541/55813379-f4f52900-5aec-11e9-9224-5b4eea3221ba.jpg)

**Comment by Evbern** [comment]
@Fredsr  Dans le message à destination du candidat, peut-on garantir que l'administration le contactera pour l'aider à trouver un nouveau créneau, suite à l'annulation administrative ?

**Comment by Evbern** [comment]
https://drive.google.com/drive/folders/1MLKobtc0RePeFU9tYnga2TW86A4LpZog

**Comment by baudointran** [comment]
TECH: - seuls les IPCSR disponibles sur le même centre, le même jour, au même horaire sont proposés

API: Récupérer les places avec le même centre, le même jours et le mêne horaire

**Comment by Evbern** [comment]
Ok pour moi
