### ISSUE TITLE
Affecter un candidat sur un créneau (dispo)

### ISSUE THREAD

**Issue by Fredsr** [LAB-MI/candilibV2#258]
ETD, je peux réserver pour le compte d'un candidat afin de l'aider à retrouver rapidement une place (ex : suite à une annulation administrative, une difficulté d'accès à la plateforme, etc.)

- [x] je clique sur un créneau disponible
- [x] une popup apparaît et me propose d'affecter le créneau à un candidat ou d'annuler l'action (via une croix)

Si j'affecte le créneau à un candidat
- [x] une barre permet de rechercher les candidats par leur numéro NEPH ou leur nom
- [x] dans cette barre de recherche, seuls les candidats non archivés et ayant un ETG valide (ie. obtenu il y a 5 ans ou moins) pour la date de la réservation sont proposés
- [x] pas de contrôle que le candidat a déjà une réservation ni qu'il a déjà réussi à la pratique (ces vérifications seront réalisées par le répartiteur)
- [x] si le candidat disposait déjà d'une réservation, la prise de rdv par l'admin remplace la réservation du candidat
- [x] pas de contrôle sur les délais (ex : après échec, annulation, date de résa)
- [x] je confirme le choix du candidat
- [x] je sélectionne le candidat et un message de confirmation avec les infos du candidat (neph, nom, prénom) est affiché
- [x] lorsque je reviens sur le planning général, le créneau est réservé pour le candidat
- [x] le créneau n'est plus disponible pour réservation par un autre candidat
- [x] pas de contrôle sur la date (modification possible jusqu'au jour J)

Si j'annule mon action
- [x] la pop-up disparaît et j'ai de nouveau accès au planning
- [x] le créneaux reste à son état initial (disponible ou indisponible)

**Comment by Evbern** [comment]
https://drive.google.com/drive/folders/1MLKobtc0RePeFU9tYnga2TW86A4LpZog

**Comment by Evbern** [comment]
Ok pour moi

**Comment by laruiss** [comment]
Qu'est-ce qui est OK ? Est-ce que tous les points peuvent être cochés ?

**Comment by laruiss** [comment]
Ce ticket est à découper, il contient trop de choses.
