### ISSUE TITLE
Télécharger le bordereau inspecteur

### ISSUE THREAD

**Issue by heydine** [LAB-MI/candilibV2#259]
1. [x] ETD, je peux demander à recevoir par mail tous les bordereaux dans le corps de mail des inspecteurs d'un département pour une date que je choisis

Doit apparaître sur le bordereau (sur modèle déjà transmis par Amandine à Stan) :
- [x] date du jour de l'examen (en haut)
- [x] nom de l'inspecteur (en haut)
- [x] nom candidat 
- [x] prénom candidat
- [x] numéro neph
- [x] case résultat 

Point d'attention : vérifier que les mails ne sont pas considérés comme des spams
