### ISSUE TITLE
Afficher le planning

### ISSUE THREAD

**Issue by laruiss** [LAB-MI/candilibV2#266]
ETD, je vois le planning des places déjà chargées.
- [x] je peux visualiser le numéro de la semaine du jour concerné
- [x] je vois les places d'un centre d'un seul jour (par défaut, le jour même)
- [x] je peux changer de centre
- [x] je peux choisir une autre date (date picker)
- [x] je peux choisir un autre centre (un des 6)

- [x] je vois les affectations des IP avec une ligne par IP (jusqu'à 14 IP) (uniquement la liste des inspecteurs en lignes, qui ont au moins un créneau sur la journée sélectionnée)
- [x] je vois 13 colonnes correspondants aux 13 créneaux
- [x] sur chaque case (créneau), un picto informe le statut du créneau
- [x] resserrer les espaces entre les cases
- [x] 3 statuts possibles : disponible, réservé, indisponible*
* disponible (icone coche verte) : créneau proposé à la réservation sans candidat positionnée 
* réservé (icone smiley bleu) : un candidat a réservé le créneau
* indisponible (icone stationnement interdit en rouge) : créneau non proposé à la réservation

**Comment by Evbern** [comment]
Ok fonctionnellement mais :
- lenteurs (+5 secs) dans le chargement des plannings et dans la réalisation d'actions liées à la modification d'un attribut du créneau (ex : statut, IPCSR, candidat)
- la 13e colonne est tronquée
