### ISSUE TITLE
Enrichir la liste des candidats

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#290]
- [ ] Ajouter le numéro de téléphone
- [ ] Ajouter le statut VIP
- [ ] Filtrer automatiquement sur le département de l'admin (c'est-à-dire uniquement les candidats inscrits dont l'adresse est déclarée dans le département de l'admin)
- [ ] Ajouter la date de réservation annulée administrativement, pour les VIP
- [ ] Pouvoir exporter la liste (bonus)

**Comment by laruiss** [comment]
Cette liste des candidats n'existe plus. Je ferme donc ce ticket. Les infos demandées seront présentes sur la fiche candidat lors d'une recherche
