### ISSUE TITLE
Annuler des créneaux en masse pour un IPCSR

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#293]
ETD, je peux annuler tous les créneaux d'une journée suite à un empêchement incombant à l'administration (ex : absence d'un inspecteur, erreur de disponibilité dans le CSV repérée tardivement).

- [x] je clique sur le nom de l'inspecteur
- [x] une popup apparaît et me propose d'annuler tous les créneaux de la journée ou d'annuler l'action (via une croix)

Si j'annule tous les créneaux de la journée ou demi-j pour l'inspecteur concerné
- [x] le délai de 45 jours n'est pas appliqué
- [x] un mail d'annulation administrative* est envoyé aux candidats
- [x] tous les créneaux (réservés et disponibles) de la journée ou demi-j de l'inspecteur deviennent indisponibles sur le site admin
- [x] les créneaux ne sont plus visibles sur le site candidat

Si j'annule mon action
- [x] la pop-up disparaît et j'ai de nouveau accès au planning

Message annulation administrative :

"Madame, Monsieur XXX,

Votre réservation à ${nameCentre} le ${dateResa} à ${houreResa} a été annulée suite à un imprévu qui incombe à l'administration.
Vous serez contacté dans les prochains jours pour replanifier un créneau dans les meilleurs délais.
Vous pouvez aussi solliciter le service administratif dédié (lien vers la section de la FAQ avec le contact des administrations) dès à présent.

L'équipe Candilib"

**Comment by baudointran** [comment]
Étape de réalisation:
- [ ]  Pouvoir annuler une réservation d'un créneaux
- [ ] Le candidat réservé doit devenir VIP. S'il y a un pénalité, il est supprimé (même s'il a échoué à l'examen)

**Comment by baudointran** [comment]
@Evbern @jclaudan @laruiss 
- S'il y a un problème d'envoi du mail annulation, doit-on proposer un renvoie de mail d’annulation ou  doit-on laissé le répartiteur le gérer?
- Si on propose un renvoi du mail où doit-on le mettre l'action?

**Comment by pli01** [comment]
test en qualif OK
