### ISSUE TITLE
Rendre disponible un créneau indisponible (3)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#297]
ETD, je veux rendre disponible un créneau indisponible, afin d'ouvrir une place à la réservation.

Critères d'acceptation :
- [x] je clique sur un créneau indisponible
- [x] une popup apparaît et me propose de le rendre disponible ou d'annuler mon action (via une croix)

Si je rends le créneau disponible
- [x] ce dernier est bien disponible sur le site candidat
- [x] pas de contrôle sur la date (modification possible jusqu'au jour J)

Si j'annule mon action
- [x] la pop-up disparaît et j'ai de nouveau accès au planning
- [x] le créneau est maintenu indisponible

**Comment by Evbern** [comment]
https://drive.google.com/drive/folders/1MLKobtc0RePeFU9tYnga2TW86A4LpZog

**Comment by Evbern** [comment]
Ok pour moi
