### ISSUE TITLE
Rendre indisponible un créneau disponible (3)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#298]
ETD, je veux rendre indisponible un créneau disponible, afin d'empêcher toute réservation (ex : absence d'un inspecteur, erreur de saisie dans le CSV).

Critères d'acceptation
- [x] je clique sur un créneau disponible
- [x] une popup apparaît et me propose de le rendre indisponible ou d'annuler mon action (via une croix)

Si je rends le créneau indisponible
- [x] il est indisponible à la réservation sur le site candidat (ce créneau n'est plus proposé)
- [x] pas de contrôle sur la date (modification possible jusqu'au jour J)

Si un candidat s'est positionné dessus pendant l'action
- [x] un message d'erreur apparaît : "Le créneau est réservé par un candidat"
- [x] je ne peux pas rendre le créneau indisponible

Si j'annule mon action
- [x] la pop-up disparaît et j'ai de nouveau accès au planning
- [x] le créneau est maintenu disponible

**Comment by Evbern** [comment]
https://drive.google.com/drive/folders/1MLKobtc0RePeFU9tYnga2TW86A4LpZog

**Comment by Evbern** [comment]
Ok pour moi

**Comment by baudointran** [comment]
Bug: Si un candidat s'est positionné dessus pendant l'action

un message d'erreur apparaît : "Le créneau est réservé par un candidat"
je ne peux pas rendre le créneau indisponible
