### ISSUE TITLE
Annuler un créneau réservé

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#302]
ETD, je peux annuler un créneau réservé suite à un empêchement incombant à l'administration (ex : absence d'un inspecteur, erreur de disponibilité dans le CSV repérée tardivement, etc.).

- [x] je clique sur un créneau réservé
- [x] une popup apparaît et me propose de confirmer l'annulation du créneau ou d'annuler mon action (via une croix)

Si j'annule le créneau réservé
- [x] le candidat réservé devient VIP (date de réservation annulée archivée)
- [ ] dans les infos de recherche du candidat, le statut VIP avec la date de réservation annulée est affiché
- [x] le délai de 45 jours n'est pas appliqué
- [x] un mail d'annulation administrative* est envoyé au candidat
- [x] le créneau devient indisponible
- [x] le créneau n'est plus visible sur le site candidat

Si j'annule mon action
- [x] la pop-up disparaît et j'ai de nouveau accès au planning
- [x] le créneau est toujours réservé par le candidat

Message annulation administrative :

"Madame, Monsieur XXX,

Votre réservation à ${nameCentre} le ${dateResa} à ${houreResa} a été annulée suite à un imprévu lié à l'administration.
Vous serez contacté dans les prochains jours pour replanifier un créneau dans les meilleurs délais.
Vous pouvez aussi solliciter le service administratif dédié (lien vers la section de la FAQ avec le contact des administrations) dès à présent.

L'équipe Candilib"

**Comment by baudointran** [comment]
Quel est l'objet du mail?

**Comment by baudointran** [comment]
@Evbern : A confirmer
"Madame, Monsieur XXX,

Votre réservation à ${nameCentre} le ${dateResa} à ${houreResa} a été annulée suite à un imprévu qui incombe à l'administration.
Vous serez contacté dans les prochains jours pour replanifier un créneau à votre convenance.
Vous pouvez aussi solliciter le service administratif dédié (lien vers la section de la FAQ avec le contact des administrations) dès à présent.

L'équipe Candilib"

**Comment by baudointran** [comment]
@Evbern @laruiss 
Il n'y a pas de contact des administrations dans le FAQ. Est-il prévu de modifier la FAQ?

**Comment by Evbern** [comment]
@baudointran @laruiss 
Oui il faudra modifier la FAQ. Je demande les contacts à Fred dans la foulée.

**Comment by Evbern** [comment]
@baudointran 
Ok pour le message !

**Comment by Evbern** [comment]
https://drive.google.com/drive/folders/1MLKobtc0RePeFU9tYnga2TW86A4LpZog

**Comment by Evbern** [comment]
@laruiss la popup de validation n'apparaît pas (tests IE)

**Comment by laruiss** [comment]
@jclaudan Où est-ce que ça en est, ça ?

**Comment by laruiss** [comment]
@Evbern Je propose qu'on ferme ce ticket et qu'on en crée un autre avec le dernier point non traité, qui doit être noté comme dépendant d'un autre ticket de gestion des VIP.

**Comment by Evbern** [comment]
@laruiss Ok parfait
