### ISSUE TITLE
Disposer de statistiques en page d'accueil

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#366]
ETD, je souhaite disposer des statistiques suivantes sur la page d'accueil de Candilib
- [ ] Histogrammes présentant le nb de candidats inscrits** sans réservation, de candidats inscrits avec réservation et de places disponibles (cf. maquette lab)
- [ ] Taux de réussite (nb reçus / (nb reçus + échecs) sur les 30 derniers jours
- [ ] Taux d'absence (nb absents / (nb non examinés*** + échecs + reçus + absents) sur les 30 derniers jours

ETD, je souhaite pouvoir disposer des données suivantes tous les _fréquence à valider_ pour réaliser statistiques, en dehors de Candilib
- [ ] Non examinés, échecs, absents, reçus
- [ ] Places proposées, réservées, annulées à  >=7 jours, annulées à < de 7 jours
- [ ] Délai entre la date d'inscription et la date de prise de résa
- [ ] Délai entre la date de prise de résa et la date de la résa
- [ ] Délai entre la date d'annulation par le candidat et la date de la nouvelle résa
- [ ] Délai entre la date d'annulation par l'admin et la date de la nouvelle résa (_à confirmer)_

** = adresse validée, éligibilité confirmée via Aurige
*** = non recevables + non examinables + annulés

**Comment by laruiss** [comment]
@Evbern Il faudrait que le fichier Excel cité soit inclus dans ce ticket ;-)

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/62222621-f60bd800-b3b3-11e9-9d9e-26bf952aee38.png)

**Comment by baudointran** [comment]
![image](https://user-images.githubusercontent.com/16351036/62222762-2ce1ee00-b3b4-11e9-9b3a-730124a39820.png)
