### ISSUE TITLE
Pouvoir replier et rouvrir le champ de recherches

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#410]
ETD, je souhaite pouvoir réaliser des recherches sur les candidats et les IPCSR et pouvoir :

- [x] Replier l'espace dédié aux résultats des recherches d'informations des candidats et IPCSR via un bouton dédié
- [x] Rouvrir cet espace au besoin via ce même bouton
- [x] Rouvrir cet espace au besoin via la réalisation d'une nouvelle recherche

**Comment by Evbern** [comment]
OK
