### ISSUE TITLE
Enrichir les tableaux de bords en accueil

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#412]
ETD, je souhaite pouvoir disposer de statistiques explicitées comme suit :

- [x] Ratio "Places dispos" / "Total places" par jour avec les semaines en lignes
- [x] Affichage de 4 semaines en ligne par centre (scroll vertical)
- [x] Date de début (JJ/MM) de la semaine à gauche de la semaine
- [x] Journées non programmées en gris, journées sans place en orange (fade), journée avec dispos en vert

_Cf maquette_

**Comment by Evbern** [comment]
![IMG_5767](https://user-images.githubusercontent.com/48919541/59287626-51ea9800-8c72-11e9-8df9-e7ff9d249046.jpg)

**Comment by jclaudan** [comment]
> * vert

ange
