### ISSUE TITLE
Paramétrer le délai d'attente par département

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#441]
ETD, je dois pouvoir paramétrer un délai d'attente national : 
- [ ] Lié à la première inscription au B1 d'un candidat
- [ ] Lié à un échec
- [ ] Lié à un no show

A décrire
