### ISSUE TITLE
Disposer des données des délais sur une période

### ISSUE THREAD

**Issue by baudointran** [LAB-MI/candilibV2#581]
Associé à #366

ETD, je souhaite pouvoir disposer des données suivantes tous les fréquence à valider pour réaliser statistiques, en dehors de Candilib

- [ ]  Délai entre la date d'inscription et la date de prise de résa
- [ ]  Délai entre la date de prise de résa et la date de la résa
- [ ]  Délai entre la date d'annulation par le candidat et la date de la nouvelle résa
- [ ]  Délai entre la date d'annulation par l'admin et la date de la nouvelle résa (à confirmer)

** = adresse validée, éligibilité confirmée via Aurige
