### ISSUE TITLE
ETC - S'inscrire sur Candilib, sans whitelist (3)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#799]
ETC, je souhaite pouvoir m'inscrire sur Candilib et y choisir mon département. Pour ce faire, il convient d'apporter les modifications suivantes à la page d'inscription :
- [x] Ajout d'un champ de choix du département de passage à l'inscription
- [x] Choix du département parmi la liste déroulante des départements où Candilib est ouvert
- [x] Au clic sur le département, une check-box apparaît en-dessous du champ Département, avec le message suivant : "Je confirme choisir le département _département choisi_ pour passer mon examen"
- [x] Lorsque je confirme la check-box, le bouton "Pré-inscription" devient cliquable
- [x] Suppression du champ de l'adresse postale

<img width="672" alt="DSR - Candilib Inscription maquettes" src="https://user-images.githubusercontent.com/48919541/67700788-e69a2c00-f9ae-11e9-847b-46e152d7f6e9.PNG">

NB : à ajouter à la FAQ
Vous devez dès à présent choisir votre département de passage à l'examen. Votre choix permet à l'administration de provisionner un nombre de place d'examen suffisant pour chaque département où Candilib est disponible

**Comment by baudointran** [comment]
### TECH: 


#### API:
- [ ] Route Candidat pour récupérer la liste de départements sans la vérification de token
