### ISSUE TITLE
ETC - Consulter la landing page, sans whitelist (2)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#800]
ETC, je souhaite pouvoir consulter la landing page de Candilib pour y être informé des étapes relatives à la réservation d'un examen du permis de conduire. Pour ce faire, il convient d'apporter les modifications suivantes à la landing page :
- [x] Ajout d'une étape ("Mise en file d'attente") entre les étapes actuelles 3 et 4 
- [x] Titre de l'étape : Mise en file d'attente
- [x] Sous-titre de l'étape :  "Attente de 30 jours avant d'accéder au planning de réservation"
- [x] Description affichée lorsqu'on clique sur l'étape : "Cette mise en file d'attente vous permet de planifier votre préparation en vue de réussir votre examen du permis de conduire"
