### ISSUE TITLE
ETC - Recevoir le mail d'attente des 30 j, sans whitelist (3)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#802]
ETC, je reçois un mail à la suite de ma validation Aurige. Ce mail explique, en plus de ma validation, le délai de 30 jours avant de voir me connecter à Candilib.
- [x] Dans le mail : ajout d'un bouton "Contactez-nous" en bas du mail qui renvoie vers l'adresse mail du contact départemental
- [x] Dans le mail, lorsqu'il est en quarantaine : ajout du message suivant, en dessous du texte expliquant ma validation : "Vous devez attendre 30 jours à partir de votre validation, avant d'accéder au planning de réservation. Cette mise en file d'attente vous permet de planifier votre préparation en vue de réussir votre examen du permis de conduire. Vous pouvez à tout moment accéder à votre statut sur Votre espace.
A ce jour, il vous reste donc X (compteur) jours avant de pouvoir vous connecter".

- [x] Dans le mail, lorsqu'il n'est plus en quarantaine : ne pas ajouter le message précédent.

**Comment by laruiss** [comment]
@Evbern Pourquoi ne pas envoyer ce message aussi quand le candidat demande un magic-link en passant par le bouton "Déjà inscrit" (tant qu'il est en file d'attente), au lieu de créer une page dédiée.

**Comment by Evbern** [comment]
@laruiss issue mise à jour
