### ISSUE TITLE
ETR - Rechercher un candidat (sans whitelist)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#804]
- [x] avoir un seul résultat lorsque, je saisis un courriel exact 
- [x] avoir seulement les résultats identiques à la saisie d'un nom complet, idem pour les prénoms
- [x] et garder la possibilité d'une recherche plus large comme actuellement

**Comment by laruiss** [comment]
@Evbern 

Est-ce que ça vous convient ?

Ajouter des filtres :
- "Commence par" (précoché)
- "Finit par"
- "Recherche le nom" (précoché)
- "Recherche le prénom" (précoché)
- "Recherche le NEPH" (précoché)
- "Recherche l'adresse courriel" (précoché)

Bouton/liens :
- Tout cocher
- Tout décocher
- Par défaut

**Comment by Evbern** [comment]
ok
