### ISSUE TITLE
ETS - Ne plus afficher les messages liés à la whitelist (5)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#807]
Lister tout le contenu concerné

**Comment by baudointran** [comment]
il n'y a pas de message à modifier. Il y a que des fonctionnalités à retirer

**Comment by Carolinedanslesnuages** [comment]
INFORMATION TECH

FRONT : 

- [ ] retirer l'accès à la whiteList coté admin

- [ ] supprimer les composant ( WhiteList.vue, WhiteListed.vue, SearchEmail.vue ) 

- [ ] modifier les test cypress 

API : 
(En cours d'écriture)

**Comment by laruiss** [comment]
Faire attention à :
- Stats KPI (invités)
- Tests e2e et les beforeAll
- Pré-inscription
- Tests unitaires
