### ISSUE TITLE
ETC - Afficher page indiquant nb de j restants avant résa - FRONT (3)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#825]
ETC je clique sur le lien reçu et une page s'affiche : 

- [ ] créer une nouvelle route dans le router vue : candilib/file-attente

- [ ] Ajouter le titre : File d'attente

- [ ] message avec la couleur bleu (fond) : `Bonjour NOM DU CANDIDAT il ne vous reste plus que X jours avant de pouvoir réserver votre examen`

- [ ] un bouton outlined en blanc avec le texte retour accueil 

# Tech

- [ ] Prendre en compte la nouvelle propriété retournée dans `getMe`

- [ ] Rediriger sur une page de message si `dateAccess` n'est pas encore révolue

**Comment by laruiss** [comment]
![20191114_163701](https://user-images.githubusercontent.com/2486424/68871758-39891880-06fd-11ea-867a-7a518c902dcf.jpg)

**Comment by baudointran** [comment]
Le lien de connexion n'apparait plus sur les courriels de connexion si le candidat est en attente (voir #802 et #803)
Issu à fermer

**Comment by Evbern** [comment]
Ok @baudointran
