### ISSUE TITLE
ETC - Afficher page indiquant nb de j restants ou donnant accès à la résa- BACK (8)

### ISSUE THREAD

**Issue by Evbern** [LAB-MI/candilibV2#828]
ETC, je souhaite me connecter à Candilib (via le mail d'attente des 30j #802 ou après avoir cliqué sur le bouton "Déjà inscrit" #803) : 

- [ ] En FO, si la DateJour < DateAccess  en BO : je clique sur le magiclink et je suis renvoyé vers une page indiquant le nombre de jours restants avant que je puisse accéder à Candilib (issue #825)
- [ ] En FO, si la DateJour >= DateAccess en BO : je clique sur le magiclink et je suis renvoyé vers la page d'accueil de Candilib me permettant de choisir mon centre d'examen, parmi ceux de mon département choisi à l'inscription
- [ ] En FO, si aucune DateAccess n'est présente en BO : je clique sur le magiclink et je suis renvoyé vers la page d'accueil de Candilib me permettant de choisir mon centre d'examen, parmi ceux de mon département choisi à l'inscription

A compléter par l'équipe tech @laruiss @baudointran @jclaudan @Carolinedanslesnuages 

Après discussion technique :

# Tech

- [ ] Modifier le model de `Candidat` pour ajouter la nouvelle prop `dateAccess`
- [ ] Au passage de la validation Aurige, on stocke la date (ou +30j : à demander aux PO) dans cette propriété
- [ ] À l'appel de `getMe`, on rajoute bien cette propriété (le front aura pour charge d'en tenir compte pour afficher la bonne page avec le bon message)
- [ ] Créer (ou modifier l'existant) et utiliser un middleware pour toutes les routes privées du candidat et lui faire le retour correspondant le cas échéant
- [ ] Utiliser une variable d'env pour le nombre de jours de la file d'attente

**Comment by baudointran** [comment]
Plus d'actualité. Le nombre jours restant se trouve dans les mails de confirmation d'inscription
