### ISSUE TITLE
ETA: Lister/Supprimer/Modifier un département (8)

### ISSUE THREAD

**Issue by pli01** [LAB-MI/candilibV2#854]
ETA, je souhaite pouvoir lister/modifier/supprimer l adresse mail de contact du département.

Techniquement, cela correspond à la gestion de la collection département, contenant:
``[ {
  "_id": "93",
  "email": "email93@departement.com"
}]``

**Comment by baudointran** [comment]
Est-ce que un déléque a le droit de créer/modifier/supprimer l'e-mail?

**Comment by baudointran** [comment]
- Est-ce que Ajouter un adresse mail revient à dire créer un département?

TECH:
API:
- [ ]: Query pour la modification
- [ ]: Route/Controller département GET/PATCH
- [ ]: Route accessible à l'administrateur seulement
FRONT:
- [ ]: Tableau de département/adresse courriel
- [ ]: Gestion de modification de l'adresse courriel
- [ ]: Menu (accessibilité / icône/ route) pour accéder aux departements
? - [ ]: trie pour chaque colonne
? - [ ]: filtre/recherche de courriel
