### ISSUE TITLE
ETA : Créer un département (5)

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#888]
ETA je veux pouvoir ajouter un nouveau département ouvert à l'utilisation de Candilib.
Le département est défini par son numéro de département et son adresse mail de contact du service de gestion des places d'examen.
- [ ] le nouveau département apparaît dans la liste de l'administrateur
- [ ] le nouveau département apparaît dans la liste des départements ouverts affichés dans la FAQ (fait dans #885)
- [ ] le mail de contact du département est ajouté dans les courriels envoyés aux candidats de ce nouveau département

**Comment by baudointran** [comment]
Lié à #854
