### ISSUE TITLE
ETD : Gérer les IPCSR

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#894]
ETD je peux gérer dans une interface les IPCSR de mon département :
- [x] visualiser la liste des IPCSR de mon département
- [x] ajouter un IPCSR avec les données nom ; prénom ; matricule ; email ; (département implicite forcé avec celui du délégué)
- [x] modifier les informations d'un IPCSR

**Comment by philippeBron** [comment]
Un IPCSR ne peut être supprimer que lorsqu'il n'a plus d'examen planifié.

**Comment by laruiss** [comment]
La suppression demande un grooming. Je propose de mettre cette fonctionnalité dans un autre ticket.
