### ISSUE TITLE
ETD : Gérer les centres d'examen de mon département

### ISSUE THREAD

**Issue by philippeBron** [LAB-MI/candilibV2#895]
ETD je peux gérer les centres d'examen de mon département :
- [x] ajouter un centre sur mon département avec les informations suivantes nom ; adresse physique ; coordonées GPS (en latitude ; longitude et pas Nord/Sud) ; étiquette (qui est affiché en complément du nom dans la liste des centre)
- [x] modifier les information d'un centre
- [x] suspendre la disponibilité d'un centre (pour cause de non disponibilité d'IPCSR ou de travaux par exemple) dans ce cas, le centre n'apparaît plus dans la liste présentée aux candidats qui ne peuvent plus réserver de places même si il y en a de planifiées.

**Comment by Archibald-Perez** [comment]
Pour suspendre la disponibilité d'un centre, comment cela doit être géré au niveau des répartiteurs ? Peuvent-ils voir et/ou assigner des candidats sur ce centre ?

**Comment by philippeBron** [comment]
Pour suspendre un centre il ne faut plus qu'il y ait de place disponible à la date de suspension.
Après suspension, le centre n'est plus visible des candidats, mais reste dans la liste des centres pour les répartiteurs et délégués tant que tous les examens ne sont pas passés.

**Comment by philippeBron** [comment]
cette dernière fonction est moins prioritaire et pourrait être ressortie dans une issue à part pour éviter tout blocage sur les 3 autres fonctionnalités qui sont prioritaires.

**Comment by Archibald-Perez** [comment]
C'est noté. J'imagine que ça vaut aussi pour la suppression d'un centre.

**Comment by philippeBron** [comment]
Oui même principe pour la suppression.
