### ISSUE TITLE
wording FAQ pour fin de whitelist

### ISSUE THREAD

**Issue by JoelPagniez** [LAB-MI/candilibV2#947]
Correction du wording de la FAQ à faire pour la suppression de la whitelist
- [x] Comment ça marche ? : faire sauter le texte "Vous avez reçu une invitation nominative par mail à vous inscrire sur Candilib."
- [x] Comment ça marche ? : Vous saisirez ... ne plus faire mention de l'adresse postale mais reprendre le texte du formulaire indiquant qu'il faut choisir un département.
- [x] Je n'ai pas réussi mon examen, puis-je reprendre une place ? : Ajouter une phrase à la suite : "Vous devez, sans autre formalité, retourner dahhhhhhhhhhhhhns votre espace Candilib pour réserver une nouvelle place."
- [x] Je souhaite passer en boite automatique
Réponse : Il n'y a pas d'examens en boite automatique ou boite manuelle.
C'est le véhicule que vous utiliserez à l'examen qui déterminera si, en cas de réussite, vous avez une restriction à la seule conduite des véhicules à boite automatique ou pas.
- [x] Quels sont les pré-requis le jour de l'examen ? : Attention : en cas de mauvais état du véhicule (pneus lisses, rétroviseurs cassés ou absents, dysfonctionnement d’un feu, etc.), ou d'absence ou de non-validité d'un des documents exigés ci-dessus, pour le candidat ou son accompagnateur, l’inspecteur sera dans l’obligation réglementaire de vous refuser le passage de l’examen.

- [x] Je ne trouve pas de places disponibles
Ajouter : D'autres peuvent se libérer à tout moment par l'annulation d'un candidat ayant réservé.
